services:
  - type: web
    name: solar-survey
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false  # You'll set this manually in Render's dashboard
      - key: PYTHON_VERSION
        value: 3.9.6  # Specify a Python version compatible with your app